sudo: required

language: ruby

services:
  - docker

install: true # skip the installation step entirely

before_script:
  - sudo sysctl -w vm.max_map_count=262144 # Required for Elasticsearch

script:
  - docker-compose -f docker-compose.test.yml build --pull
  - docker-compose -f docker-compose.test.yml run --rm app sh -c "yarn lint && bundle exec rubocop"
  - docker-compose -f docker-compose.test.yml run --rm app sh -c "./docker/wait-for-services.sh && bundle exec rake db:create spec"

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export REPO=$DOCKER_USERNAME/docker-rails
  - docker-compose -f docker-compose.production.yml build

deploy:
  -
    provider: script
    script: docker tag dockerrails_app_production $REPO:latest && docker push $REPO
    on:
      branch: develop

  -
    provider: script
    script: docker tag dockerrails_app_production $REPO:${TRAVIS_TAG} && docker push $REPO
    on:
      tags: true
