version: '3.4'

services:
  db:
    environment:
      - POSTGRES_PASSWORD=my-pg-password
    hostname: db.docker-rails.my-site.com
    image: postgres:11-alpine
    ports:
      - 5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - /my-volumes/docker-rails/postgresql:/var/lib/postgresql/data

  elasticsearch:
    hostname: elasticsearch.docker-rails.my-site.com
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.3
    restart: always
    volumes:
      - /my-volumes/docker-rails/elasticsearch:/usr/share/elasticsearch/data

  redis:
    hostname: redis.docker-rails.my-site.com
    image: redis:alpine
    restart: always
    volumes:
      - /my-volumes/docker-rails/redis:/data

  backup:
    environment:
      - POSTGRES_DATABASE=docker-rails_production
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=my-pg-password
      - POSTGRES_USER=postgres
      - S3_ACCESS_KEY_ID=my-access-key-id
      - S3_BUCKET=my-bucket
      - S3_PREFIX=docker-rails
      - S3_REGION=eu-central-1
      - S3_SECRET_ACCESS_KEY=my-secret-access-key
      - SCHEDULE=@daily
    hostname: backup.docker-rails.my-site.com
    image: 'schickling/postgres-backup-s3:latest'
    links:
      - db
    restart: always

  app: &app_base
    image: dockerrails_app_production
    build:
      context: .
      args:
        - FOLDERS_TO_REMOVE=spec node_modules app/assets vendor/assets lib/assets tmp/cache
        - BUNDLE_WITHOUT=development:test
        - RAILS_ENV=production
    environment:
      - APP_ADMIN_EMAIL=mail@my-site.com
      - APP_ADMIN_PASSWORD=supergeheim
      - APP_EMAIL=reply@example.org
      - APP_HOST=docker-rails.example.org
      - AWS_ACCESS_KEY_ID=my-access-key-id
      - AWS_BUCKET=my-bucket
      - AWS_REGION=eu-central-1
      - AWS_SECRET_ACCESS_KEY=my-secret-access-key
      - BLAZER_DATABASE_URL=postgres://postgres:my-pg-password@db:5432/docker-rails_production
      - CERT_NAME=docker-rails.my-site.com
      - DB_HOST=db
      - DB_PASSWORD=my-pg-password
      - DB_USER=postgres
      - ELASTICSEARCH_HOST=elasticsearch
      - LETSENCRYPT_EMAIL=mail@my-site.com
      - LETSENCRYPT_HOST=docker-rails.my-site.com
      - PIWIK_HOST=piwik.my-site.com
      - PIWIK_ID=my-piwik-id
      - RAILS_ENV=production
      - RAILS_MAX_THREADS=5
      - REDIS_CABLE_URL=redis://redis:6379/1
      - REDIS_SIDEKIQ_URL=redis://redis:6379/0
      - REDIS_CACHE_URL=redis://redis:6379/2
      - ROLLBAR_ACCESS_TOKEN=my-rollbar-token
      - SECRET_KEY_BASE=my-secret-access-key
      - SKYLIGHT_AUTHENTICATION=my-skylight-authentication
      - SMTP_AUTHENTICATION=plain
      - SMTP_DOMAIN=docker-rails.my-site.com
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_PASSWORD=my-smtp-password
      - SMTP_PORT=587
      - SMTP_SERVER=smtp.sendgrid.net
      - SMTP_USERNAME=my-sendgrid-apikey
      - VIRTUAL_HOST=docker-rails.my-site.com
    hostname: app.docker-rails.my-site.com
    links:
      - db
      - elasticsearch
      - redis
    ports:
      - 3000
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 5m
      start_period: 1m

  worker:
    <<: *app_base
    command: bundle exec sidekiq
    hostname: worker.docker-rails.my-site.com
    healthcheck:
      test: "ps ax | grep -v grep | grep sidekiq"
      interval: 1m
      start_period: 1m
