version: '3.4'
services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.5
    volumes:
      - es-data:/usr/share/elasticsearch/data

  redis:
    image: redis:alpine

  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 5900:5900

  app:
    image: dockerrails_app_test
    build:
      context: .
      args:
        - ADDITIONAL_PACKAGES=nodejs yarn
        - BUNDLE_WITHOUT=production
        - RAILS_ENV=test
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      REDIS_SIDEKIQ_URL: redis://redis:6379/0
      REDIS_CABLE_URL: redis://redis:6379/1
      REDIS_CACHE_URL: redis://redis:6379/2
      SELENIUM_REMOTE_HOST: selenium
      RAILS_ENV: test
      DB_HOST: db
      POSTGRES_PASSWORD: duubidoo
      SECRET_KEY_BASE: we-dont-need-a-secret-here
      DB_USER: postgres
      DB_PASSWORD: duubidoo
      APP_ADMIN_EMAIL: admin@example.org
      APP_ADMIN_PASSWORD: secret
      APP_EMAIL: reply@example.org
      APP_HOST: example.org
      AWS_ACCESS_KEY_ID: my-access-key
      AWS_SECRET_ACCESS_KEY: my-secret
      AWS_BUCKET: my-bucket
      AWS_REGION: eu-central-1
    ports:
      - 3000
    links:
      - elasticsearch
      - db
      - redis
      - selenium

volumes:
  db-data:
  es-data:
